# Generated by Django 3.1.11 on 2021-07-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(default='TBA', max_length=255, unique=True)),
                ('code', models.CharField(max_length=5, null=True)),
                ('department', models.CharField(blank=True, choices=[('Computer Science', '1.Computer Science'), ('Business', '2.Business')], max_length=255, null=True)),
                ('price', models.FloatField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='df.png', upload_to='')),
                ('major', models.CharField(blank=True, choices=[('Computer Science', '1.Computer Science'), ('Business', '2.Business')], max_length=255, null=True)),
                ('phone_nb', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, choices=[('Beirut', '1.Beirut'), ('Baabda', '2.Baabda'), ('Byblos', '3.Byblos')], max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(default='TBA', max_length=255, unique=True)),
                ('department', models.CharField(blank=True, choices=[('Computer Science', '1.Computer Science'), ('Business', '2.Business')], max_length=255, null=True)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Code_FK', to='School_MS.allcourses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
