# Generated by Django 3.1.11 on 2021-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_MS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='time',
            field=models.CharField(default='TBA', max_length=255, null=True),
        ),
    ]
