# Generated by Django 3.1.11 on 2021-07-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_MS', '0002_courses_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='grade',
            field=models.CharField(default='Not Available Yet', max_length=3, null=True),
        ),
    ]
